import Head from "next/head";
import { Carousel } from "@/components/Carousel";

interface HomeProps {
  data: Car[];
}

export default function Home({ data }: HomeProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        <Carousel />
      </div>
    </>
  );
}
